import 'antd/lib/table/style';
import _Table from 'antd/lib/table';
import 'antd/lib/result/style';
import _Result from 'antd/lib/result';
import 'antd/lib/date-picker/style';
import _DatePicker from 'antd/lib/date-picker';
import 'antd/lib/button/style';
import _Button from 'antd/lib/button';
import { registerNode } from '@top-datav/core';
import drawReactNode from './drawReactNode';
import WebPage from '../WebPage';
import ProductQueue from '../../customMade/ProductQueue';
import PDMonthReport from '../../customMade/PDMonthReport';
import DataTable from '../dataTable';
import LiveVideo from '../LiveVideo';
import QTLiveVideo from '../QTLiveVideo';
import DateFormat from '../DateFormat';
export function register() {
  registerNode('button', drawReactNode(_Button), null, null, null);
  registerNode('datePicker', drawReactNode(_DatePicker), null, null, null);
  registerNode('result', drawReactNode(_Result), null, null, null);
  registerNode('table', drawReactNode(_Table), null, null, null);
  registerNode('webPage', drawReactNode(WebPage), null, null, null);
  registerNode('productQueue', drawReactNode(ProductQueue), null, null, null);
  registerNode('pdMonthReport', drawReactNode(PDMonthReport), null, null, null);
  registerNode('dataTable', drawReactNode(DataTable), null, null, null);
  registerNode('liveVideo', drawReactNode(LiveVideo), null, null, null);
  registerNode('QTLiveVideo', drawReactNode(QTLiveVideo), null, null, null);
  registerNode('dateFormat', drawReactNode(DateFormat), null, null, null);
}
